name: Browser Publish

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Publish
        run: dotnet publish -c Release -o ./publish WebTranslator/WebTranslator.Browser

      - name: Clone GitHub Pages Repository
        env:
          GH_TOKEN: ${{ secrets.CFPATools_Token }}
        run: |
          git clone https://x-access-token:${GH_TOKEN}@github.com/CFPATools/cfpatools.github.io.git gh-pages

      - name: Copy Files to GitHub Pages Repository
        run: |
          cp -r ./publish/wwwroot/* ./gh-pages/
          cd gh-pages
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "$(date +'%Y-%m-%d') Action"
          git push origin master
