name: Desktop Publish

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      
      # Add MsBuild to the PATH: https://github.com/microsoft/setup-msbuild
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2

      - name: Publish
        run: dotnet publish -c Release -o ./publish WebTranslator/WebTranslator.Desktop

      - name: Rename and Clean Windows Files
        run: |
          mv publish/WebTranslator.Desktop.exe publish/WebTranslator.exe
          rm -f publish/WebTranslator.Desktop.pdb publish/WebTranslator.pdb

      - name: Package Windows Build
        run: |
          cd publish
          Compress-Archive -Path * -DestinationPath ../WebTranslator-windows_amd64.zip
          cd ..

      - name: Upload Windows Build
        uses: actions/upload-artifact@v2
        with:
          name: WebTranslator-windows_amd64.zip
          path: WebTranslator-windows_amd64.zip
  
  build-ubuntu:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y clang zlib1g-dev p7zip-full

      - name: Publish
        run: dotnet publish -c Release -o ./publish WebTranslator/WebTranslator.Desktop

      - name: Rename and Clean Ubuntu Files
        run: |
          mv publish/WebTranslator.Desktop publish/WebTranslator
          rm -f publish/WebTranslator.Desktop.dbg publish/WebTranslator.pdb

      - name: Package Ubuntu Build
        run: |
          cd publish
          7z a -ttar WebTranslator-linux_amd64.tar .
          7z a -tgzip ../WebTranslator-linux_amd64.tar.gz WebTranslator-linux_amd64.tar
          rm WebTranslator-linux_amd64.tar
          cd ..

      - name: Upload Ubuntu Build
        uses: actions/upload-artifact@v2
        with:
          name: WebTranslator-linux_amd64.tar.gz
          path: WebTranslator-linux_amd64.tar.gz
  
  release:
    needs: [build-windows, build-ubuntu]
    runs-on: ubuntu-latest
    steps:
      - name: Download Windows Build
        uses: actions/download-artifact@v2
        with:
          name: WebTranslator-windows_amd64.zip
          path: release/windows

      - name: Download Ubuntu Build
        uses: actions/download-artifact@v2
        with:
          name: WebTranslator-linux_amd64.tar.gz
          path: release/ubuntu
